### PR TITLE
feat: voucher types

### PR DESCRIPTION
**Pull request by nksazonov**

### CODE REVIEW

**Review by mod — CHANGES_REQUESTED** [review]
Looks valid, but 
Rename freeMint/Meld by
MintByVoucher
MeldByVoucher

You are missing setPrice methods for mint and meld

**Comment by nksazonov** [comment]
> Looks valid, but Rename freeMint/Meld by MintByVoucher MeldByVoucher

I don't think sharing technical details of Rewards (term `Voucher`) implementation from the `Garden` to the `Ducklings` is a good idea. However, I agree, we can have a better naming for `free mint/meld`. 
 
> You are missing setPrice methods for mint and meld

Those will be added in the PR regarding Ducklings.

**Comment by mod** [comment]
image

I would keep the Ducklings strictly as empty as possible, and only let the Garden construct all Ducklings
either using a Voucher or by Collecting a payment
Technically we could have 1 or several entry point to access those features.

Melding is a game feature, which involves 5 existing Ducklings and compute a new DNA out of those 5 DNA
then it can ask the Ducklings contract to construct a new Duckie with this specific DNA.

it would not make sense that a Duckling has the ability to meld 5 into a new Duckie

Eventually, the only upgradable contract would be Garden, while Ducklings could be versionned.
We can create new generation, maybe mapping specific collections or adding features.

But that's to be confirmed

**Comment by nksazonov** [comment]
> I would keep the Ducklings strictly as empty as possible, and only let the Garden construct all Ducklings
either using a Voucher or by Collecting a payment

The voucher is sent from the Back-end. So if we make Garden main, and the only entry point to the Ducklings, this will mean, that only the Back-end controls the minting process. This is the opposite of what we were seeking to achieve when moving Ducklings generation from the Back-end to the Blockchain. That is why I think your approach contradicts our philosophy of fully Blockchain NFT generation.

Moreover, moving melding logic to Garden complicates things. Firstly, melding needs randomness logic, which is present in the Ducklings (where minting happens). Secondly, melding also needs info on trait values, which is also stored in the Ducklings. Thus, melding is tightly coupled with the Ducklings contract, and keeping Garden and Ducklings logic separate satisfies the Separation of concerns principle. I see more harm than good in moving it to the Garden contract.

**Comment by mod** [comment]
> The voucher is sent from the Back-end. So if we make Garden main, and the only entry point to the Ducklings, this will mean, that only the Back-end controls the minting process. This is the opposite of what we were seeking to achieve when moving Ducklings generation from the Back-end to the Blockchain. That is why I think your approach contradicts our philosophy of fully Blockchain NFT generation.

That's not what I am describing here:
- mintByPayment is accessible directly by the user, without voucher, transfer the amount to self
- mintByVoucher is calling the same single method to mint the NFT

About melding logic, I sort of understand the problem, let me take a closer look now in my IDE.

**Comment by nksazonov** [comment]
> That's not what I am describing here:
mintByPayment is accessible directly by the user, without voucher, transfer the amount to self
mintByVoucher is calling the same single method to mint the NFT

I see. Correct, you don't need to go via the Back-end to mint the NFT.
However, if you want to have both methods only in the Garden, there is no possibility to mint in Ducklings directly. This couples Ducklings to the Garden very tightly and makes these two contracts and their development even more co-dependent. That is, if something happens to the Garden that makes it inoperable, it would make Ducklings inoperable too!

Nevertheless, we could not decouple minting and melding and put them both into the Garden. But this would complicate things even more by introducing much more logic and, more importantly, storage variables (collections, trait values) to the Garden. This huge amount of storage variables will make developing the next versions of the Garden much harder, as we must keep this same storage layout.

The aforementioned complications point out that keeping the Garden and the Ducklings separate **will only complement the development and maintenance** of both, but _may slightly_ harm the philosophy of melding (that it is better to put it in the Garden)

**Pull request merged**
